# رمزهای امضای اپ — این فایل را هرگز جایی share نکنید و حتماً بکاپ بگیرید.
storeFile=../hamdast-release.jks
storePassword=4eDsOVBUA8GTQjjzFFdAbSD5O8cUBwO7
keyAlias=hamdast
keyPassword=4eDsOVBUA8GTQjjzFFdAbSD5O8cUBwO7
